<?php
/**
 * @file
 * Create the necessary hooks to make a revert to last revision vbo action.
 *
 * Originally found from:
 * https://www.drupal.org/node/1166630
 *
 * The above didnt work fully so I debugged this for bulk and single nodes
 * using an sqlite drupal environment.
 * http://drupal.stackexchange.com/questions/180838/revert-to-last-revision-action/
 */

/**
 * Implements hook_action_info().
 */
function revert_last_revision_action_info() {
  $action = array(
    'revert_to_last_revision' => array(
      'label'        => t('Revert to Last Revision'),
      'type'         => 'node',
      'configurable' => FALSE,
      'triggers'     => array('any'),
      // I believe this view_property causes the 2nd save to not occur as it's
      // not a save action -- aka in our custom function we do our own save
      // which will not be overwritten.
      'behavior'     => array('view_property'),
    ),
  );
  return $action;
}

/**
 * Action function for revert_to_last_revision.
 */
function revert_to_last_revision(&$entity, $context = array()) {
  $revision_list = node_revision_list($entity);
  unset($revision_list[$entity->vid]);
  if (count($revision_list) > 0) {
    $last_revision = max(array_keys($revision_list));
    $entity = entity_revision_load('node', $last_revision);
    $entity->revision = TRUE;
    $entity->log = "Reverted via bulk operation action.";
    entity_save('node', $entity);
  }
}
